name: "Update manifest"
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0
    - name: Install nixFlake
      uses: cachix/install-nix-action@v27
      with:
        install_url: https://github.com/nix-community/nix-unstable-installer/releases/download/nix-2.23.0pre20240603_da92ad7/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Configure git
      run: |
        git config --global user.name 'Automation - Ninlives'
        git config --global user.email 'wqseleven@gmail.com'
    - name: Nix flake update
      run: nix flake update --commit-lock-file
    - name: Update
      run: nix run .#update
    - name: Commit
      run: |
        if [ -z "$(git status --porcelain)" ]; then
          echo "working directory is clean, skip commit and push"
        else
          git add .
          git commit -am "Update manifest - Automated Commit"
          git push
        fi
